# Important Notes:
# fabric.mod.json's modid field cannot be expanded, you must change it manually.
# Every field you add must be added to the root build.gradle expandProps map.

# Project
group=de.cech12.unlitcampfire
mod_version=3.1.1.2
mod_id=unlitcampfire
mod_name=Unlit Campfire
mod_author=Cech12
mod_license=The MIT License (MIT)
mod_url=https://github.com/cech12/UnlitCampfire
mod_issue_tracker=https://github.com/cech12/UnlitCampfire/issues
description=A mod where placed campfires are unlit.

# Common
java_version=21
minecraft_version=1.21
minecraft_version_range=[1.21, 1.22)

# Fabric
fabric_version=0.100.3+1.21
fabric_loader_version=0.15.11
cloth_config_version=15.0.127
mod_menu_version=11.0.1

# Forge
forge_version=51.0.17
forge_version_range=[51.0.17,)
forge_loader_version_range=[51,)

# NeoForge
neoforge_version=21.0.94-beta
neoforge_version_range=[21.0.94-beta,)
neoforge_loader_version_range=[2,)

#jade
jade_fabric_id=5427840
jade_fabric_version=15.0.4
jade_neoforge_id=5444008
jade_neoforge_version_range=[15.0.5,)

#the one probe
top_version=1.21_neo-12.0.0-1
top_version_range=[1.21_neo-12.0.0,)

# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false