modLoader="javafml"
loaderVersion="${neoforge_loader_version_range}"
issueTrackerURL="${mod_issue_tracker}"
license="${mod_license}"
[[mods]]
modId="${mod_id}"
version="${version}"
displayName="${mod_name}"
displayURL="${mod_url}"
logoFile="logo.png"
authors="${mod_author}"
description='''${mod_description}'''
[[mixins]]
config = "${mod_id}.mixins.json"
[[accessTransformers]]
file="META-INF/accesstransformer.cfg"
[[dependencies.${mod_id}]]
modId="neoforge"
type="required"
versionRange="${neoforge_version_range}"
ordering="NONE"
side="BOTH"
[[dependencies.${mod_id}]]
modId="minecraft"
type="required"
versionRange="${minecraft_version_range}"
ordering="NONE"
side="BOTH"
[[dependencies.${mod_id}]]
modId="jade"
type="optional"
versionRange="${jade_neoforge_version_range}"
referralUrl="https://www.curseforge.com/minecraft/mc-mods/jade"
ordering="NONE"
side="BOTH"
